// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ExMCsQ8bclaRGD3eWd4XXNND2zcLJoI',
    appId: '1:243486098123:web:96bd07415782f58547114e',
    messagingSenderId: '243486098123',
    projectId: 'study-app-91054',
    authDomain: 'study-app-91054.firebaseapp.com',
    storageBucket: 'study-app-91054.appspot.com',
    measurementId: 'G-BG223S08GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXO2m9Ui0SH917mLpUHGlAtpTrmR3Ino',
    appId: '1:243486098123:android:3fecdce9501ac6ce47114e',
    messagingSenderId: '243486098123',
    projectId: 'study-app-91054',
    storageBucket: 'study-app-91054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt875jLyaTfqQIygoOuhbTYAsayxIRLhA',
    appId: '1:243486098123:ios:97889471634a952f47114e',
    messagingSenderId: '243486098123',
    projectId: 'study-app-91054',
    storageBucket: 'study-app-91054.appspot.com',
    iosClientId: '243486098123-goso6feiq6d9g48vctgrori7jbk8tong.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt875jLyaTfqQIygoOuhbTYAsayxIRLhA',
    appId: '1:243486098123:ios:97889471634a952f47114e',
    messagingSenderId: '243486098123',
    projectId: 'study-app-91054',
    storageBucket: 'study-app-91054.appspot.com',
    iosClientId: '243486098123-goso6feiq6d9g48vctgrori7jbk8tong.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
